### ISSUE TITLE
rsblocks panicked

### ISSUE THREAD

**Issue by AngelBerihuete** [MustafaSalih1993/rsblocks#57]
I've updated rsblocks but when I tried to execute from terminal this message is showed:
```bash
thread 'main' panicked at 'Failed to create x11 connection: FailedToConnect', src/types.rs:151:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by MustafaSalih1993** [comment]
AngelBerihuete
please rebuild with the following and reply since the issue information is not enough to debug
```sh
git clone https://github.com/MustafaSalih1993/rsblocks
cd rsblocks
cargo install --path .
```

**Comment by AngelBerihuete** [comment]
The problem persists. I've followed your advise cloning the repo in my ~/gitrepos directory. Then I've installed rsblocks with cargo. I've tried to execute inside rsblocks/target/release directory with the same result

```
rsblocks/target/release on master (base) > ls
build  deps  examples  incremental  rsblocks  rsblocks.d
rsblocks/target/release on master (base) > rsblocks
thread 'main' panicked at 'Failed to create x11 connection: FailedToConnect', src/types.rs:151:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by MustafaSalih1993** [comment]
Ahh i tried to reproduce this i couldn't find out, i will try to have a better error handling and outputting a more helpful error messages, the message for now saying it failing to connect to your Xorg session nothing else

**Comment by AngelBerihuete** [comment]
Thanks @MustafaSalih1993 I'll wait to the next release to try rsblocks.

**Comment by c02y** [comment]
The similar error message but from `src/blockmanager.rs:12:48`

```
>> RUST_BACKTRACE=1 ./target/release/rsblocks
thread 'main' panicked at 'Failed to create x11 connection: FailedToConnect', src/blockmanager.rs:12:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
   3: rsblocks::blockmanager::BlockManager::new
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: std::thread::local::LocalKey<T>::with
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: async_io::driver::block_on
   8: async_global_executor::executor::block_on
   9: std::thread::local::LocalKey<T>::with
  10: std::thread::local::LocalKey<T>::with
  11: async_std::task::builder::Builder::blocking
  12: rsblocks::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by MustafaSalih1993** [comment]
Current build of rsblocks breaks and didn't fix _yet_ due to some personal life situations and lack of contributions.

**users**_(if any)_ can use an older version of rsblocks that depends on older versions of breadx library, until development continues or some people contribute.

**Comment by AngelBerihuete** [comment]
Thank you very much for rsblocks @MustafaSalih1993 ! I hope that everything goes well.
